<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Agam-PC" failures="0" tests="6" name="Practise.ListenersPractise" time="5.523" errors="1" timestamp="2023-02-13T23:05:36 IST" skipped="3">
  <testcase classname="Practise.ListenersPractise" name="methodtwo" time="0.001"/>
  <system-out/>
  <testcase classname="Practise.ListenersPractise" name="methodOne" time="0.358">
    <error message="this is exception !!" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: this is exception !!
at Practise.ListenersPractise.methodOne(ListenersPractise.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- methodOne -->
  <system-out/>
  <testcase classname="Practise.ListenersPractise" name="driverSetUp" time="2.595"/>
  <system-out/>
  <testcase classname="Practise.ListenersPractise" name="methodOne" time="1.178">
    <skipped/>
  </testcase> <!-- methodOne -->
  <system-out/>
  <testcase classname="Practise.ListenersPractise" name="methodOne" time="0.879">
    <skipped/>
  </testcase> <!-- methodOne -->
  <system-out/>
  <testcase classname="Practise.ListenersPractise" name="methodOne" time="0.512">
    <skipped/>
  </testcase> <!-- methodOne -->
  <system-out/>
</testsuite> <!-- Practise.ListenersPractise -->
